name: Auto Format
on:
  push:
    branches: [ main ] # Запускати при кожному пуші в гілку main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Prettier
        uses: creyD/prettier_action@v4.6
        with:
          # Вкажіть типи файлів, які потрібно форматувати
          prettier_options: --write **/*.{js,ts,md,html,css,json}
          only_changed: true # Форматувати лише змінені файли
